-- SCRIPT DDL: CRIAÇÃO DO ESQUEMA
-- Configuração do ID Sequencial
-- Para MySQL/MariaDB:
-- CREATE TABLE Categoria (
--     ID_Categoria INT PRIMARY KEY AUTO_INCREMENT,
--     Nome VARCHAR(100) NOT NULL UNIQUE
-- );

-- Para PostgreSQL:
CREATE TABLE CATEGORIA (
    ID_Categoria SERIAL PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE PRODUTO (
    ID_Produto SERIAL PRIMARY KEY,
    ID_Categoria INT NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    Descricao TEXT,
    Preco_Base DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_Categoria) REFERENCES CATEGORIA(ID_Categoria) ON DELETE RESTRICT
);

CREATE TABLE VARIAÇÃO (
    ID_Variacao SERIAL PRIMARY KEY,
    ID_Produto INT NOT NULL,
    Cor VARCHAR(50),
    Tamanho VARCHAR(50),
    SKU VARCHAR(50) UNIQUE NOT NULL, -- Stock Keeping Unit
    Estoque_Atual INT NOT NULL DEFAULT 0 CHECK (Estoque_Atual >= 0),
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto) ON DELETE CASCADE
);

CREATE TABLE CLIENTE (
    ID_Cliente SERIAL PRIMARY KEY,
    Nome_Completo VARCHAR(255) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    Data_Cadastro DATE NOT NULL
);

CREATE TABLE ENDERECO (
    ID_Endereco SERIAL PRIMARY KEY,
    ID_Cliente INT NOT NULL,
    Rua VARCHAR(255) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Estado CHAR(2) NOT NULL,
    CEP CHAR(8) NOT NULL,
    Tipo_Endereco VARCHAR(50), -- Ex: 'Principal', 'Trabalho'
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente) ON DELETE CASCADE
);

CREATE TABLE PEDIDO (
    ID_Pedido SERIAL PRIMARY KEY,
    ID_Cliente INT NOT NULL,
    ID_Endereco_Entrega INT NOT NULL,
    Data_Pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(50) NOT NULL, -- Ex: 'Pendente', 'Pago', 'Enviado'
    Valor_Total DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente) ON DELETE RESTRICT,
    FOREIGN KEY (ID_Endereco_Entrega) REFERENCES ENDERECO(ID_Endereco) ON DELETE RESTRICT
);

CREATE TABLE ITEM_PEDIDO (
    ID_Pedido INT NOT NULL,
    ID_Variacao INT NOT NULL,
    Quantidade INT NOT NULL CHECK (Quantidade > 0),
    Preco_Unitario_Vendido DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_Pedido, ID_Variacao),
    FOREIGN KEY (ID_Pedido) REFERENCES PEDIDO(ID_Pedido) ON DELETE CASCADE,
    FOREIGN KEY (ID_Variacao) REFERENCES VARIAÇÃO(ID_Variacao) ON DELETE RESTRICT
);

CREATE TABLE AVALIACAO (
    ID_Avaliacao SERIAL PRIMARY KEY,
    ID_Cliente INT NOT NULL,
    ID_Produto INT NOT NULL,
    Nota SMALLINT NOT NULL CHECK (Nota BETWEEN 1 AND 5),
    Comentario TEXT,
    Data DATE DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente) ON DELETE RESTRICT,
    FOREIGN KEY (ID_Produto) REFERENCES PRODUTO(ID_Produto) ON DELETE RESTRICT
);
